import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import Navbar from '@/components/Navbar';

import { Toaster } from 'sonner';

import { getSession } from '@/lib/getSession';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getSession();
  return (
    <html lang="es" className="dark">
      <body>
        <Toaster
          position="top-center"
          toastOptions={{
            unstyled: true,
            classNames: {
              toast:
                'bg-[#18181b] rounded-lg text-danger p-4 flex items-center gap-2 border border-danger-400 shadow-sm',
            },
          }}
        />
        <Navbar session={session} />
        <main className="relative container mx-auto max-w-7xl z-10 px-6 min-h-[calc(100vh_-_64px_-_108px)] mb-12 flex-grow">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
